#!/usr/bin/env python3
"""
build_coverage.py — DD-0002 pipeline: Step 1 verdicts + Step 2 embed context.

Step 1 (verdict management):
    python scripts/build_coverage.py --status               # Pipeline status
    python scripts/build_coverage.py --batches               # Generate all batches
    python scripts/build_coverage.py --batches --chapter 3    # Ch3 batches only
    python scripts/build_coverage.py --merge FILE --chapter 3 # Merge verdicts
    python scripts/build_coverage.py --normalize              # Normalize formats
    python scripts/build_coverage.py --redistribute           # Redistribute wrong_chapter
    python scripts/build_coverage.py --redistribute --round 2 # Round 2+
    python scripts/build_coverage.py --resolve                # Force-assign bouncing findings

Step 2 (embed context assembly):
    python scripts/build_coverage.py --embed-prep --chapter 4 # Step 2 context packages
    python scripts/build_coverage.py --validate                # Validate ALL Step 2 batches
    python scripts/build_coverage.py --validate --validate-path FILE  # Validate one file

MANDATORY: Run --validate before any Step 2 evaluation. Ad-hoc batch assembly is
forbidden (see PM-0003). All batches must be generated by --embed-prep.
"""

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SOURCES_DIR = PROJECT_ROOT / "sources"
YOUTUBE_DIR = SOURCES_DIR / "youtube"
COVERAGE_DIR = SOURCES_DIR / "coverage"

BATCH_SIZE = 250  # findings per batch

# Import the existing extraction parser
sys.path.insert(0, str(Path(__file__).resolve().parent))
from review_extractions import parse_all_extractions


def load_inventory(chapter: int) -> list:
    """Load the coverage inventory for a chapter."""
    path = COVERAGE_DIR / f"ch{chapter}_inventory.json"
    if not path.exists():
        return []
    return json.loads(path.read_text())


def load_verdicts(chapter: int) -> dict:
    """Load existing verdicts for a chapter. Returns {finding_id: verdict_dict}."""
    path = COVERAGE_DIR / f"ch{chapter}_validation_verdicts.json"
    if not path.exists():
        return {}

    data = json.loads(path.read_text())

    # Normalize: dict format (ch3) → standard lookup
    if isinstance(data, dict):
        result = {}
        for fid, v in data.items():
            verdict = v.get("verdict") or v.get("step1_verdict", "")
            result[fid] = {
                "finding_id": fid,
                "verdict": verdict,
                "justification": v.get("justification", ""),
            }
        return result

    # Array format (all other chapters)
    result = {}
    for entry in data:
        fid = entry.get("finding_id", "")
        if fid:
            result[fid] = entry
    return result


def save_verdicts(chapter: int, verdicts: dict):
    """Save verdicts in standardized array format."""
    path = COVERAGE_DIR / f"ch{chapter}_validation_verdicts.json"
    # Convert to sorted array
    arr = sorted(verdicts.values(), key=lambda x: x.get("finding_id", ""))
    path.write_text(json.dumps(arr, indent=2, ensure_ascii=False))


def get_all_findings_by_chapter() -> dict:
    """Parse all extractions and group by primary chapter."""
    findings = parse_all_extractions()
    by_chapter = defaultdict(list)
    for f in findings:
        for ch in f.chapter_nums:
            by_chapter[ch].append(f)
    return by_chapter


def cmd_status(args):
    """Show pipeline status."""
    by_chapter = get_all_findings_by_chapter()

    print("DD-0002 Step 1 Pipeline Status")
    print("=" * 65)
    print(f"{'Ch':<4} {'Total':<8} {'Evaluated':<10} {'Remaining':<10} {'Inventory':<10}")
    print("-" * 65)

    total_all = 0
    eval_all = 0

    for ch in sorted(by_chapter.keys()):
        if ch == 0:
            continue  # skip preface
        total = len(by_chapter[ch])
        verdicts = load_verdicts(ch)
        evaluated = len(verdicts)
        inventory = load_inventory(ch)
        inv_count = len(inventory)
        remaining = total - evaluated

        total_all += total
        eval_all += evaluated

        print(f"Ch{ch:<3} {total:<8} {evaluated:<10} {remaining:<10} {inv_count:<10}")

    print("-" * 65)
    print(f"{'All':<4} {total_all:<8} {eval_all:<10} {total_all - eval_all:<10}")

    # Show verdict distribution for evaluated findings
    print("\nVerdict Distribution (evaluated findings):")
    all_verdicts = Counter()
    for ch in sorted(by_chapter.keys()):
        if ch == 0:
            continue
        verdicts = load_verdicts(ch)
        for v in verdicts.values():
            verdict = v.get("verdict", "unknown")
            all_verdicts[verdict] += 1

    for verdict, count in all_verdicts.most_common():
        pct = count / eval_all * 100 if eval_all > 0 else 0
        print(f"  {verdict:<16} {count:>4} ({pct:.1f}%)")


def cmd_batches(args):
    """Generate self-contained evaluation batches.

    Each batch includes: findings, chapter inventory, full chapter text,
    cross-chapter inventories, and anti-pattern rules. The evaluating
    agent does not need to load anything separately.
    """
    by_chapter = get_all_findings_by_chapter()
    chapters = [args.chapter] if args.chapter else sorted(ch for ch in by_chapter if ch > 0)

    COVERAGE_DIR.mkdir(parents=True, exist_ok=True)
    batches_dir = COVERAGE_DIR / "batches"
    batches_dir.mkdir(parents=True, exist_ok=True)

    total_batches = 0

    for ch in chapters:
        findings = by_chapter.get(ch, [])
        if not findings:
            print(f"Ch{ch}: No findings")
            continue

        if args.force:
            unevaluated = findings
        else:
            existing = load_verdicts(ch)
            unevaluated = [f for f in findings if f.finding_id not in existing]

        if not unevaluated:
            print(f"Ch{ch}: All {len(findings)} findings already evaluated")
            continue

        inventory = load_inventory(ch)
        if not inventory:
            print(f"Ch{ch}: WARNING — no inventory found, skipping")
            continue

        # Context: chapter text + Q&A (global + chapter) + cross-chapter inventories
        chapter_path = PROJECT_ROOT / f"chapter{ch}.tex"
        chapter_text = chapter_path.read_text() if chapter_path.exists() else ""

        global_qa_path = PROJECT_ROOT / "scripts" / "global_qa.md"
        global_qa = global_qa_path.read_text() if global_qa_path.exists() else ""
        qa_path = PROJECT_ROOT / "scripts" / f"ch{ch}_qa.md"
        chapter_qa = qa_path.read_text() if qa_path.exists() else ""
        qa_text = ""
        if global_qa:
            qa_text += "=== GLOBAL Q&A (applies to all chapters) ===\n\n" + global_qa
        if chapter_qa:
            if qa_text:
                qa_text += "\n\n"
            qa_text += f"=== CHAPTER {ch} Q&A ===\n\n" + chapter_qa

        cross_chapter = {}
        for other_ch in range(1, 7):
            if other_ch == ch:
                continue
            inv = load_inventory(other_ch)
            if inv:
                cross_chapter[f"chapter_{other_ch}"] = inv

        # Generate batches
        ch_batches = []
        for i in range(0, len(unevaluated), BATCH_SIZE):
            batch_findings = unevaluated[i:i + BATCH_SIZE]
            batch = {
                "chapter": ch,
                "batch_index": len(ch_batches),
                "total_batches_for_chapter": -1,  # filled below
                "anti_pattern_rules": ANTI_PATTERN_RULES,
                "findings": [
                    {
                        "finding_id": f.finding_id,
                        "channel": f.channel,
                        "video_title": f.video_title,
                        "status": f.status,
                        "description": f.description,
                        "quote": f.quote,
                    }
                    for f in batch_findings
                ],
                "chapter_inventory": inventory,
                "chapter_text": chapter_text,
                "qa_history": qa_text,
                "cross_chapter_inventories": cross_chapter,
            }
            ch_batches.append(batch)

        for b in ch_batches:
            b["total_batches_for_chapter"] = len(ch_batches)

        for b in ch_batches:
            batch_path = batches_dir / f"ch{ch}_batch_{b['batch_index']:03d}.json"
            batch_path.write_text(json.dumps(b, indent=2, ensure_ascii=False))

        total_batches += len(ch_batches)
        print(f"Ch{ch}: {len(unevaluated)} unevaluated findings → {len(ch_batches)} batches")

    print(f"\nTotal: {total_batches} batches written to {batches_dir}/")


def cmd_merge(args):
    """Merge agent verdict results into chapter verdict files."""
    if not args.chapter:
        print("ERROR: --chapter required with --merge", file=sys.stderr)
        return 1

    merge_path = Path(args.merge)
    if not merge_path.exists():
        print(f"ERROR: {merge_path} not found", file=sys.stderr)
        return 1

    new_data = json.loads(merge_path.read_text())

    # Support both array and dict formats from agents
    new_verdicts = {}
    if isinstance(new_data, list):
        for entry in new_data:
            fid = entry.get("finding_id", "")
            if fid:
                new_verdicts[fid] = entry
    elif isinstance(new_data, dict):
        for fid, v in new_data.items():
            new_verdicts[fid] = {"finding_id": fid, **v}

    existing = load_verdicts(args.chapter)
    added = 0
    updated = 0
    for fid, verdict in new_verdicts.items():
        if fid in existing:
            updated += 1
        else:
            added += 1
        existing[fid] = verdict

    save_verdicts(args.chapter, existing)
    print(f"Ch{args.chapter}: merged {added} new + {updated} updated → {len(existing)} total")


def cmd_normalize(args):
    """Normalize all verdict files to array format."""
    for ch in range(1, 7):
        verdicts = load_verdicts(ch)
        if not verdicts:
            continue
        save_verdicts(ch, verdicts)
        print(f"Ch{ch}: normalized {len(verdicts)} verdicts to array format")


MAX_REDISTRIB_ROUNDS = 3


def parse_target_chapter(entry: dict, source_ch: int) -> int | None:
    """Extract target chapter from a wrong_chapter verdict.

    Handles three formats:
    1. explicit suggested_chapter field (int like 4, or string like "ch5")
    2. regex "Chapter N" in justification text
    3. regex "Chapter N" in rationale text
    Returns target chapter int, or None if unparseable.
    """
    # Method 1: explicit suggested_chapter field
    sc = entry.get("suggested_chapter")
    if sc is not None:
        if isinstance(sc, int):
            if 1 <= sc <= 6 and sc != source_ch:
                return sc
        elif isinstance(sc, str):
            # Handle "ch5", "Ch3", "chapter 4", or bare "5"
            m = re.search(r"(\d)", sc)
            if m:
                ch = int(m.group(1))
                if 1 <= ch <= 6 and ch != source_ch:
                    return ch

    # Method 2/3: regex from justification or rationale
    text = entry.get("justification", "") or entry.get("rationale", "")
    if not text:
        return None

    matches = re.findall(r"[Cc]hapter\s*(\d)", text)
    targets = [int(m) for m in matches if int(m) != source_ch and 1 <= int(m) <= 6]
    if targets:
        return targets[0]

    # Also try "Ch3" / "ch5" patterns (common in verdict text)
    matches = re.findall(r"[Cc]h\s*(\d)", text)
    targets = [int(m) for m in matches if int(m) != source_ch and 1 <= int(m) <= 6]
    if targets:
        return targets[0]

    return None


def load_verdict_files(chapter: int, round_num: int) -> list[dict]:
    """Load verdict entries from appropriate files for a given round.

    Round 1: scans ch{N}_step1_batch_*.json and ch{N}_verdicts_opus_*.json
    Round 2+: scans ch{N}_verdicts_opus_redistrib_r{round-1}.json only
    """
    entries = []

    if round_num == 1:
        seen = set()

        # Current format: step1 batch verdict files
        pattern = f"ch{chapter}_step1_batch_*.json"
        for path in sorted(COVERAGE_DIR.glob(pattern)):
            data = json.loads(path.read_text())
            if isinstance(data, list):
                for e in data:
                    fid = e.get("finding_id", "")
                    if fid not in seen:
                        seen.add(fid)
                        entries.append(e)

        # Legacy format: opus verdict files (excluding redistrib files)
        pattern = f"ch{chapter}_verdicts_opus_*.json"
        for path in sorted(COVERAGE_DIR.glob(pattern)):
            if "redistrib" in path.name:
                continue
            data = json.loads(path.read_text())
            if isinstance(data, list):
                for e in data:
                    fid = e.get("finding_id", "")
                    if fid not in seen:
                        seen.add(fid)
                        entries.append(e)
            elif isinstance(data, dict):
                for fid, v in data.items():
                    if fid not in seen:
                        seen.add(fid)
                        entries.append({"finding_id": fid, **v})

        # Also check consolidated validation_verdicts
        val_path = COVERAGE_DIR / f"ch{chapter}_validation_verdicts.json"
        if val_path.exists():
            data = json.loads(val_path.read_text())
            if isinstance(data, list):
                for e in data:
                    fid = e.get("finding_id", "")
                    if fid not in seen:
                        seen.add(fid)
                        entries.append(e)
            elif isinstance(data, dict):
                for fid, v in data.items():
                    if fid not in seen:
                        seen.add(fid)
                        entries.append({"finding_id": fid, **v})
    else:
        # Round 2+: only previous round's redistribution verdicts
        prev = round_num - 1
        seen = set()

        # Current format: step1 redistrib verdict files
        step1_path = COVERAGE_DIR / f"ch{chapter}_step1_redistrib_r{prev}.json"
        if step1_path.exists():
            data = json.loads(step1_path.read_text())
            if isinstance(data, list):
                for e in data:
                    fid = e.get("finding_id", "")
                    if fid not in seen:
                        seen.add(fid)
                        entries.append(e)

        # Legacy format: opus redistrib verdict files
        legacy_path = COVERAGE_DIR / f"ch{chapter}_verdicts_opus_redistrib_r{prev}.json"
        if legacy_path.exists():
            data = json.loads(legacy_path.read_text())
            if isinstance(data, list):
                for e in data:
                    fid = e.get("finding_id", "")
                    if fid not in seen:
                        seen.add(fid)
                        entries.append(e)
            elif isinstance(data, dict):
                for fid, v in data.items():
                    if fid not in seen:
                        seen.add(fid)
                        entries.append({"finding_id": fid, **v})

    return entries


def cmd_redistribute(args):
    """Redistribute wrong_chapter findings to correct chapters."""
    round_num = args.round or 1

    if round_num > MAX_REDISTRIB_ROUNDS:
        print(f"ERROR: max {MAX_REDISTRIB_ROUNDS} redistribution rounds", file=sys.stderr)
        return 1

    # Build finding content lookup from parse_all_extractions()
    all_findings = parse_all_extractions()
    content_by_id = {}
    for f in all_findings:
        content_by_id[f.finding_id] = {
            "finding_id": f.finding_id,
            "text": f.description,
            "quote": f.quote,
        }

    # Fallback: alexandria_reextraction.json
    reextract_path = COVERAGE_DIR / "alexandria_reextraction.json"
    if reextract_path.exists():
        reextract = json.loads(reextract_path.read_text())
        for entry in reextract:
            fid = entry.get("finding_id", "")
            if fid and fid not in content_by_id:
                content_by_id[fid] = {
                    "finding_id": fid,
                    "text": entry.get("text", ""),
                    "quote": entry.get("quote", ""),
                }

    # Load previous-round redistribution history for ping-pong detection
    prev_redistributed = set()
    if round_num >= 2:
        for prev_round in range(1, round_num):
            for ch in range(1, 7):
                path = COVERAGE_DIR / f"ch{ch}_findings_redistrib_r{prev_round}.json"
                if path.exists():
                    data = json.loads(path.read_text())
                    for entry in data:
                        prev_redistributed.add(entry.get("finding_id", ""))

    # Collect wrong_chapter verdicts from all chapters
    # Key: target_chapter -> list of {finding_id, text, quote, source_ch}
    by_target = defaultdict(list)
    unparseable = []
    ping_pong = []
    total_wrong = 0

    for source_ch in range(1, 7):
        entries = load_verdict_files(source_ch, round_num)
        for entry in entries:
            if entry.get("verdict") != "wrong_chapter":
                continue

            total_wrong += 1
            fid = entry.get("finding_id", "")

            target = parse_target_chapter(entry, source_ch)
            if target is None:
                unparseable.append((fid, source_ch, entry))
                continue

            # Ping-pong detection: finding redistributed in a previous round
            if fid in prev_redistributed:
                ping_pong.append((fid, source_ch, target))
                continue

            # Look up content
            content = content_by_id.get(fid)
            if content is None:
                print(f"  WARNING: no content for {fid} (source ch{source_ch})")
                continue

            # Safety: target must differ from source
            if target == source_ch:
                continue

            by_target[target].append({
                "finding_id": fid,
                "text": content["text"],
                "quote": content["quote"],
                "source_chapter": source_ch,
            })

    # Print summary
    print(f"Redistribution Round {round_num}")
    print("=" * 55)
    print(f"Total wrong_chapter verdicts: {total_wrong}")

    if not by_target:
        print("\nNo findings to redistribute. Converged.")
        if unparseable:
            print(f"\n{len(unparseable)} unparseable (no target chapter detected):")
            for fid, sch, _ in unparseable:
                print(f"  {fid} (from ch{sch})")
        if ping_pong:
            print(f"\n{len(ping_pong)} ping-pong (flagged for manual review):")
            for fid, sch, tgt in ping_pong:
                print(f"  {fid}: ch{sch} → ch{tgt}")
        return 0

    print(f"\nRedistribution:")
    total_redistributed = 0
    for target_ch in sorted(by_target.keys()):
        findings = by_target[target_ch]
        sources = Counter(f["source_chapter"] for f in findings)
        source_str = ", ".join(f"ch{s}:{c}" for s, c in sorted(sources.items()))
        print(f"  → Ch{target_ch}: {len(findings)} findings (from {source_str})")
        total_redistributed += len(findings)

    # Write batch files
    COVERAGE_DIR.mkdir(parents=True, exist_ok=True)
    files_written = []

    for target_ch in sorted(by_target.keys()):
        findings = by_target[target_ch]
        out_path = COVERAGE_DIR / f"ch{target_ch}_findings_redistrib_r{round_num}.json"
        out_data = [
            {
                "finding_id": f["finding_id"],
                "text": f["text"],
                "quote": f["quote"],
                "source_chapter": f["source_chapter"],
            }
            for f in findings
        ]
        out_path.write_text(json.dumps(out_data, indent=2, ensure_ascii=False))
        files_written.append(out_path.name)

    print(f"\n{total_redistributed} findings → {len(files_written)} batch files:")
    for name in files_written:
        print(f"  {COVERAGE_DIR / name}")

    if unparseable:
        print(f"\n{len(unparseable)} unparseable (no target chapter detected):")
        for fid, sch, _ in unparseable:
            print(f"  {fid} (from ch{sch})")

    if ping_pong:
        print(f"\n{len(ping_pong)} ping-pong (flagged for manual review):")
        for fid, sch, tgt in ping_pong:
            print(f"  {fid}: ch{sch} → ch{tgt}")

    return 0


def cmd_resolve(args):
    """Generate forced-resolution batch files for unplaceable findings.

    After redistribution rounds, some findings keep bouncing between chapters.
    This command collects all unresolved findings (ping-pong + still wrong_chapter),
    groups them by their two candidate chapters, and writes batch files for agents
    that read BOTH chapters and make a final assignment.

    Usage:
        python scripts/build_coverage.py --resolve
    """
    # Build finding content lookup
    all_findings = parse_all_extractions()
    content_by_id = {}
    for f in all_findings:
        content_by_id[f.finding_id] = {
            "text": f.description,
            "quote": f.quote,
        }

    # Fallback: alexandria_reextraction.json
    reextract_path = COVERAGE_DIR / "alexandria_reextraction.json"
    if reextract_path.exists():
        reextract = json.loads(reextract_path.read_text())
        for entry in reextract:
            fid = entry.get("finding_id", "")
            if fid and fid not in content_by_id:
                content_by_id[fid] = {
                    "text": entry.get("text", ""),
                    "quote": entry.get("quote", ""),
                }

    # Collect all redistribution verdict files to find wrong_chapter findings
    # and trace their routing history
    r1_input = {}  # finding_id -> {redistrib_to, source_chapter}
    for path in sorted(COVERAGE_DIR.glob("ch*_findings_redistrib_r1.json")):
        ch_num = int(path.name.split("_")[0][2])
        data = json.loads(path.read_text())
        for item in data:
            fid = item.get("finding_id", "")
            r1_input[fid] = {
                "redistrib_to": ch_num,
                "source_chapter": item.get("source_chapter", 0),
            }

    r1_wrong = {}  # finding_id -> {evaluated_in, suggested_target}
    for path in sorted(COVERAGE_DIR.glob("ch*_step1_redistrib_r1.json")):
        ch_num = int(path.name.split("_")[0][2])
        data = json.loads(path.read_text())
        for item in data:
            if item.get("verdict") != "wrong_chapter":
                continue
            fid = item["finding_id"]
            just = item.get("justification", "")
            targets = re.findall(r"[Cc]hapter\s*(\d)", just)
            targets += re.findall(r"[Cc]h\s*(\d)", just)
            target_chs = [int(t) for t in targets if int(t) != ch_num and 1 <= int(t) <= 6]
            r1_wrong[fid] = {
                "evaluated_in": ch_num,
                "suggested_target": target_chs[0] if target_chs else None,
            }

    r2_wrong = {}
    for path in sorted(COVERAGE_DIR.glob("ch*_step1_redistrib_r2.json")):
        ch_num = int(path.name.split("_")[0][2])
        data = json.loads(path.read_text())
        for item in data:
            if item.get("verdict") != "wrong_chapter":
                continue
            fid = item["finding_id"]
            just = item.get("justification", "")
            targets = re.findall(r"[Cc]hapter\s*(\d)", just)
            targets += re.findall(r"[Cc]h\s*(\d)", just)
            target_chs = [int(t) for t in targets if int(t) != ch_num and 1 <= int(t) <= 6]
            r2_wrong[fid] = {
                "evaluated_in": ch_num,
                "suggested_target": target_chs[0] if target_chs else None,
            }

    r2_input_fids = set()
    for path in sorted(COVERAGE_DIR.glob("ch*_findings_redistrib_r2.json")):
        data = json.loads(path.read_text())
        for item in data:
            r2_input_fids.add(item.get("finding_id", ""))

    # Build unresolved set: r2 wrong_chapter + ping-pong (r1 wrong_chapter not in r2)
    all_unresolved = {}

    for fid, info in r2_wrong.items():
        all_unresolved[fid] = (info["evaluated_in"], info["suggested_target"])

    for fid, info in r1_wrong.items():
        if fid not in r2_input_fids and fid not in r2_wrong:
            orig = r1_input.get(fid, {})
            all_unresolved[fid] = (
                info["evaluated_in"],
                info["suggested_target"] or orig.get("source_chapter"),
            )

    if not all_unresolved:
        print("No unresolved findings. All redistributions converged.")
        return 0

    # Group by chapter pair
    by_pair = defaultdict(list)
    no_pair = []
    for fid, (a, b) in all_unresolved.items():
        if a and b and a != b:
            pair = tuple(sorted([a, b]))
            c = content_by_id.get(fid, {"text": "", "quote": ""})
            by_pair[pair].append({
                "finding_id": fid,
                "text": c["text"],
                "quote": c["quote"],
                "candidate_chapters": list(pair),
            })
        else:
            no_pair.append(fid)

    # Write per-pair batch files
    files_written = []
    total = 0
    for pair in sorted(by_pair.keys()):
        findings = by_pair[pair]
        out_path = COVERAGE_DIR / f"pingpong_ch{pair[0]}_ch{pair[1]}.json"
        out_path.write_text(json.dumps(findings, indent=2, ensure_ascii=False))
        files_written.append((pair, len(findings), out_path))
        total += len(findings)

    print(f"Forced Resolution: {total} unresolved findings across {len(files_written)} chapter pairs")
    print("=" * 55)
    for pair, count, path in files_written:
        print(f"  ch{pair[0]} vs ch{pair[1]}: {count} findings → {path.name}")

    if no_pair:
        print(f"\n{len(no_pair)} findings with no clear pair (need manual assignment):")
        for fid in no_pair:
            print(f"  {fid}")

    print(f"\nEach batch must be evaluated by an agent that reads BOTH chapter texts.")
    print(f"The agent MUST assign every finding — wrong_chapter is forbidden.")
    print(f"Output: sources/coverage/ch{{A}}_ch{{B}}_resolved.json")

    return 0


STEP2_RULES = [
    (
        "Step 2 verdicts — every verdict must include a justification: "
        "EMBED: finding names a specific primary source (ancient text, NT passage, "
        "inscription, papyrus, coin, published scholarly analysis of a specific "
        "text) AND gives enough concrete detail to write a sentence into the "
        "chapter. The source does NOT need to be independently re-verified by "
        "the evaluator — if the finding names a well-known published work "
        "(Homer, Josephus, Philo, Eusebius, specific NT verse, specific "
        "inscription corpus, a named scholar's published analysis of a specific "
        "passage), it is grounded enough. EMBED means 'this can go to ChatGPT "
        "for drafting now.' Do NOT default to RESEARCH out of caution — if the "
        "finding cites a real, named, published source with a specific claim, "
        "it is EMBED unless you have a concrete reason to doubt it. "
        "RESEARCH: finding makes a claim worth investigating but either (a) does "
        "not name the primary source, (b) names a source but the specific claim "
        "cannot be located from the finding text alone, (c) makes a quantitative "
        "claim that needs checking (e.g. 'appears 80 times'), or (d) attributes "
        "a position to an ancient author without quoting or citing the specific "
        "passage. RESEARCH goes to research_gaps.md with what source is needed "
        "and where to look. Nothing is rejected for being 'unverified' or "
        "'speculative.' RESEARCH is the fallback for findings that are not "
        "clearly a restate, not clearly tangential, and not already rejected "
        "in Q&A — but the evaluator MUST NOT use RESEARCH as a lazy default "
        "when EMBED clearly applies. "
        "SKIP: restates — the chapter (or Q&A) already presents THE SAME SPECIFIC "
        "EVIDENCE (same inscription, same verse, same ancient author quote) AND "
        "draws THE SAME CONCLUSION from it. The justification MUST quote the "
        "chapter passage (with line number) that makes the finding redundant. "
        "Vague 'chapter covers this topic' or 'chapter already has a section on X' "
        "is NEVER sufficient. If the finding cites a primary source (text, "
        "inscription, coin, papyrus, ancient author passage) that the chapter does "
        "not cite — even if the chapter makes a similar argument using different "
        "sources — it is NOT a restatement; it is RESEARCH or EMBED. "
        "SKIP: tangential — true but the book doesn't need it IN ANY CHAPTER. "
        "A finding that belongs in a different chapter is NOT tangential — it is "
        "RESEARCH with cross_chapter routing. SKIP_tangential is ONLY for findings "
        "that no chapter in the book could use. "
        "SKIP: Q&A rejected — Q&A file records a prior deliberate decision to "
        "exclude this finding. Must cite the specific Q&A entry. "
        "QA: the finding is valid but either the argument is weaker than "
        "what the book already has, or the topic is already highly "
        "saturated in the chapter. It goes "
        "straight to Q&A as a documented note — no further research needed. "
        "This keeps background topics from bloating the book while preserving "
        "the finding for the record. "
        "There is NO 'weak' verdict. The evaluator does not reject findings "
        "based on subjective quality judgments."
    ),
    (
        "CRITICAL: No finding may be rejected because ChatGPT cannot verify it. "
        "'ChatGPT says it's unsubstantiated' is not a SKIP reason — it is a "
        "RESEARCH reason. ChatGPT lies often due to bias. It halluccinates "
        "sources, fabricates references, and presents its gaps as fact. Listen "
        "to ChatGPT, never trust it. 'ChatGPT confirmed X' is a lead, not "
        "verification. 'ChatGPT couldn't find X' means nothing."
    ),
    (
        "Cross-chapter check: if another chapter contains a deeper or more "
        "developed treatment of the same argument, the new material belongs "
        "there — merged into the existing section, not duplicated. The goal "
        "is one authoritative treatment per argument, not parallel versions. "
        "CRITICAL: 'belongs in another chapter' is NOT a SKIP reason. A finding "
        "that is valuable for the book but belongs in a different chapter MUST "
        "be assigned RESEARCH (or EMBED) with the cross_chapter field set to "
        "the target chapter (e.g. 'ch3'). SKIP_tangential means 'the book does "
        "not need this anywhere' — not 'this chapter does not need this.' If "
        "the finding serves ANY argument in ANY chapter, it is NOT tangential."
    ),
    (
        "Section-fit check: before inserting text into a specific section, "
        "verify (1) the new text does not contradict the chapter's own thesis, "
        "and (2) the new text serves the argument of the section it is placed "
        "in. If the text doesn't serve the section's argument, find the section "
        "it does serve — or create one."
    ),
    (
        "Q&A check: if the Q&A file records a deliberate decision to exclude "
        "something, respect it. Do not resurface findings that were already "
        "researched and rejected."
    ),
    (
        "Source framing vs underlying observation: evaluate the OBSERVATION, "
        "not the source's FRAMING. A finding from an unconventional source "
        "with sensationalist language may contain a valid structural observation. "
        "Extract the observation, discard the framing. Example: a speaker says "
        "'John was recruiting cutthroats for an army' — the sensationalist "
        "language is the framing; the observation is 'baptism functioned as an "
        "organizational recruitment/initiation rite for a political movement.' "
        "The observation fits an institutional-framework thesis perfectly. "
        "NEVER use the source's tone, reputation, or platform as a reason to "
        "SKIP. Judge the observation on its structural merit. If the observation "
        "is valid but unsourced, the verdict is RESEARCH, not SKIP."
    ),
    (
        "Rejections require documented decisions. A SKIP verdict is only valid "
        "when grounded in something verifiable: the finding restates existing "
        "content (checkable against inventory), the finding is tangential "
        "(no argument in any chapter it could serve), or Q&A records a prior "
        "decision to exclude it. Subjective judgments — 'too extreme,' 'would "
        "weaken credibility,' 'too thin,' 'contradicts consensus' — are not "
        "valid SKIP reasons. If a finding serves any argument the book makes "
        "and has not been rejected in Q&A, the verdict is EMBED or RESEARCH. "
        "CRITICAL: a source may provide excellent data but draw a wrong "
        "conclusion. We reject the conclusion and embed the data. Example: "
        "a mythicist presents detailed Eleusinian mystery parallels to "
        "Christian initiation rites, then concludes 'Jesus never existed.' "
        "The conclusion is wrong per the book, but the mystery cult data "
        "strengthens the book's argument about Greek institutional origins. "
        "Never SKIP a finding because the source's conclusion is wrong — "
        "extract the data, discard the bad conclusion."
    ),
]


ANTI_PATTERN_RULES = [
    (
        "Keyword extraction is forbidden in any form: extracting words from "
        "text A, searching for them in text B, and drawing any conclusion "
        "from matches. See PM-0001, PM-0002."
    ),
    (
        "Scripts present information for human review. Scripts never assign "
        "verdicts based on mechanical text matching."
    ),
    (
        "No automated status assignment (CLEAR, FLAGGED, NEEDS_REVIEW, KEEP, "
        "SKIP) based on text matching."
    ),
    (
        "COVERED verdict anti-patterns — three forbidden shortcuts: "
        "(1) Topic-level match: 'book argues X, finding argues X, therefore "
        "covered' is WRONG. Must name the specific evidence the finding brings "
        "AND where the book already presents that same specific evidence. "
        "(2) 'Same argument' without evidence comparison: 'ch1 makes this exact "
        "argument' is not enough. Does the book already present this specific "
        "scholar's framing, this specific quote, this specific example? If any "
        "of these are new, verdict is new_evidence_existing_argument, not "
        "covered. "
        "(3) Implicit coverage: 'the concept is implicit in the framework' or "
        "'this is a variant of what is covered' means the book does NOT state it "
        "— therefore NOT covered. Any of these prevent a covered verdict: a named "
        "concept the book doesn't use, a specific mechanism the book doesn't "
        "describe, a new scope claim, or a new specific source text (e.g., book "
        "has Mark-Homer mimesis but finding has Mark-Aeneid — different source, "
        "not a variant). Test: does the inventory list this exact item? If you "
        "must argue it is 'implied by' or 'a variant of' an existing item, it "
        "is NOT covered."
    ),
    (
        "The verdict matrix has two axes — is the ARGUMENT new, and is the "
        "EVIDENCE new? "
        "covered: argument in book AND evidence in book (or Q&A addresses it). "
        "new_evidence_existing_argument: argument in book, evidence NOT in "
        "book — new evidence to bolster an existing argument. "
        "new_argument_existing_evidence: argument NOT in book, evidence IS in "
        "book — someone looked at the same source we cite and drew a different "
        "conclusion. Often the most valuable: data already verified, only the "
        "argument is new. Do NOT downgrade to new_evidence_existing_argument "
        "or covered just because the evidence appears in the book. "
        "new_evidence_and_argument: argument NOT in book, evidence NOT in "
        "book — both need evaluation."
    ),
    (
        "Distinguish weak evidence from weak reasoning. "
        "Weak evidence can be valuable as a supporting argument. "
        "Weak reasoning means the claim simply does not follow from "
        "the evidence — reject it."
    ),
    (
        "Parallels to universal human activities are not evidence of "
        "historical connection — every culture has communal meals, "
        "processions, washing rituals, mourning. But specific details "
        "within universal activities CAN be evidence: a communal meal "
        "alone proves nothing, but bread and wine symbolizing body and "
        "blood is specific. A procession alone proves nothing, but a "
        "procession carrying the body of the god with incense is "
        "specific. Judge the specificity of the shared detail, not "
        "the category of the activity."
    ),
    (
        "Background saturation. Some topics (e.g. Hellenization of the "
        "Levant) are important context but the book already establishes "
        "them. If a new finding on a background topic is weaker than or "
        "equal to what is already in the book, send it straight to Q&A "
        "— subsequent runs will see Q&A marks it as addressed. The book "
        "should not lose focus by accumulating background evidence "
        "beyond what the argument needs."
    ),
    (
        "Factual accuracy gate. Check whether the finding's claims "
        "are actually true. A finding can sound relevant and well-argued "
        "but rest on a factual error. If the core claim is wrong, "
        "reject it — do not embed or research a false premise."
    ),
]


STEP1_SURVIVORS = (
    "new_evidence_existing_argument",
    "new_argument_existing_evidence",
    "new_evidence_and_argument",
    "contradicts",
)


def _load_all_verdicts_for_chapter(ch: int) -> dict:
    """Collect all Step 1 verdicts for a chapter from every source.

    Sources (checked in order, deduplicated by finding_id):
    1. Main step1 batch files: ch{N}_step1_batch_*.json
    2. Redistribution verdicts: ch{N}_step1_redistrib_r*.json
    3. Forced resolution files: *_ch{N}_resolved.json and ch{N}_*_resolved.json
    4. Legacy verdict files: ch{N}_verdicts_opus_*.json, ch{N}_validation_verdicts.json

    Returns {finding_id: verdict_entry}.
    """
    seen = {}

    def _add(entries):
        for e in entries:
            fid = e.get("finding_id", "")
            if fid and fid not in seen:
                seen[fid] = e

    def _load_json_list(path):
        if not path.exists():
            return []
        data = json.loads(path.read_text())
        if isinstance(data, list):
            return data
        if isinstance(data, dict):
            return [{"finding_id": fid, **v} for fid, v in data.items()]
        return []

    # 1. Main step1 batch verdicts
    for path in sorted(COVERAGE_DIR.glob(f"ch{ch}_step1_batch_*.json")):
        _add(_load_json_list(path))

    # 2. Redistribution verdicts (all rounds)
    for path in sorted(COVERAGE_DIR.glob(f"ch{ch}_step1_redistrib_r*.json")):
        _add(_load_json_list(path))

    # 3. Forced resolution files — findings assigned TO this chapter
    for path in sorted(COVERAGE_DIR.glob("ch*_ch*_resolved.json")):
        for e in _load_json_list(path):
            if e.get("assigned_chapter") == ch:
                _add([e])

    # 4. Legacy formats
    for path in sorted(COVERAGE_DIR.glob(f"ch{ch}_verdicts_opus_*.json")):
        if "redistrib" in path.name:
            continue
        _add(_load_json_list(path))
    _add(_load_json_list(COVERAGE_DIR / f"ch{ch}_validation_verdicts.json"))

    return seen


def _load_findings_from_verdicts(ch: int) -> list[dict]:
    """Load surviving findings from Step 1 verdicts for a chapter.

    Collects from all verdict sources (step1 batches, redistribution,
    resolution, legacy). Survivors: new_evidence_existing_argument,
    new_argument_existing_evidence, new_evidence_and_argument, contradicts.
    """
    all_verdicts = _load_all_verdicts_for_chapter(ch)

    survivors = [
        v for v in all_verdicts.values()
        if v.get("verdict") in STEP1_SURVIVORS
    ]

    # Enrich with content from extraction files
    all_findings = parse_all_extractions()
    content_by_id = {f.finding_id: f for f in all_findings}

    for fallback_name in ("all_new_arguments.json", "alexandria_reextraction.json"):
        fallback_path = COVERAGE_DIR / fallback_name
        if not fallback_path.exists():
            continue
        for entry in json.loads(fallback_path.read_text()):
            fid = entry.get("finding_id", "")
            if not fid or fid in content_by_id:
                continue
            content_by_id[fid] = type("Finding", (), {
                "finding_id": fid,
                "description": entry.get("text", ""),
                "quote": entry.get("quote", ""),
                "video_title": entry.get("video_title", ""),
                "channel": entry.get("channel", ""),
            })()

    packages = []
    for v in sorted(survivors, key=lambda x: x.get("finding_id", "")):
        fid = v.get("finding_id", "")
        content = content_by_id.get(fid)
        packages.append({
            "finding_id": fid,
            "step1_verdict": v.get("verdict", ""),
            "step1_justification": v.get("justification", ""),
            "text": content.description if content else "",
            "quote": getattr(content, "quote", ""),
            "source": (
                getattr(content, "video_title", "")
                or getattr(content, "channel", "")
            ),
        })
    return packages


def _load_findings_from_batch(batch_path: Path) -> dict[int, list[dict]]:
    """Load findings from a batch file, grouped by chapter."""
    data = json.loads(batch_path.read_text())
    by_chapter = defaultdict(list)
    for entry in data:
        ch = entry.get("chapter")
        if not ch:
            continue
        by_chapter[ch].append({
            "finding_id": entry.get("finding_id", ""),
            "step1_verdict": "batch",
            "step1_justification": entry.get("justification", ""),
            "text": entry.get("text", ""),
            "quote": entry.get("quote", ""),
            "source": entry.get("source", ""),
        })
    return dict(by_chapter)


def _build_chapter_context(ch: int, findings: list[dict]) -> dict:
    """Build a Step 2 context package for one chapter.

    Includes everything the evaluator needs: findings, chapter text,
    chapter inventory, Q&A (global + chapter), cross-chapter inventories,
    anti-pattern rules, and Step 2 verdict rules. The evaluator does not
    need to load anything separately.
    """
    global_qa_path = PROJECT_ROOT / "scripts" / "global_qa.md"
    global_qa = global_qa_path.read_text() if global_qa_path.exists() else ""

    qa_path = PROJECT_ROOT / "scripts" / f"ch{ch}_qa.md"
    chapter_qa = qa_path.read_text() if qa_path.exists() else ""

    qa_text = ""
    if global_qa:
        qa_text += "=== GLOBAL Q&A (applies to all chapters) ===\n\n" + global_qa
    if chapter_qa:
        if qa_text:
            qa_text += "\n\n"
        qa_text += f"=== CHAPTER {ch} Q&A ===\n\n" + chapter_qa

    chapter_path = PROJECT_ROOT / f"chapter{ch}.tex"
    chapter_text = chapter_path.read_text() if chapter_path.exists() else ""

    chapter_inventory = load_inventory(ch)

    cross_chapter = {}
    for other_ch in range(1, 7):
        if other_ch == ch:
            continue
        inv = load_inventory(other_ch)
        if inv:
            cross_chapter[f"chapter_{other_ch}"] = inv

    return {
        "chapter": ch,
        "step2_rules": STEP2_RULES,
        "anti_pattern_rules": ANTI_PATTERN_RULES,
        "findings": findings,
        "qa_history": qa_text,
        "chapter_text": chapter_text,
        "chapter_inventory": chapter_inventory,
        "cross_chapter_inventories": cross_chapter,
    }


def cmd_embed_prep(args):
    """Assemble Step 2 embed context packages.

    Two modes:
      --embed-prep --chapter N           Survivors from Step 1 verdicts
      --embed-prep --batch FILE          Findings from a batch file

    Each context package contains: findings, anti-pattern rules, Q&A
    history, full chapter text, and cross-chapter inventories.

    The tool assembles and presents. It does not score, classify, or
    pre-filter. See DD-0002 Step 2 spec.
    """
    out_dir = COVERAGE_DIR / "embed_prep"
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.batch:
        batch_path = Path(args.batch)
        if not batch_path.exists():
            print(f"ERROR: {batch_path} not found", file=sys.stderr)
            return 1
        by_chapter = _load_findings_from_batch(batch_path)
        chapters = sorted(by_chapter.keys())
    elif args.chapter:
        findings = _load_findings_from_verdicts(args.chapter)
        if not findings:
            print(f"Ch{args.chapter}: No surviving findings for embedding")
            return 0
        by_chapter = {args.chapter: findings}
        chapters = [args.chapter]
    else:
        # All chapters
        by_chapter = {}
        for ch in range(1, 7):
            findings = _load_findings_from_verdicts(ch)
            if findings:
                by_chapter[ch] = findings
        chapters = sorted(by_chapter.keys())
        if not chapters:
            print("No surviving findings in any chapter")
            return 0

    failed = False
    for ch in chapters:
        findings = by_chapter[ch]
        output = _build_chapter_context(ch, findings)
        out_path = out_dir / f"ch{ch}_embed_context.json"
        out_path.write_text(json.dumps(output, indent=2, ensure_ascii=False))

        # Mandatory self-validation (PM-0003: never produce invalid batches)
        errors = validate_step2_batch(out_path)
        if errors:
            failed = True
            print(f"\nFAIL: {out_path.name} — generated batch is INVALID")
            for e in errors:
                print(f"  - {e}")
            out_path.unlink()  # Delete the invalid batch
            print(f"  DELETED: {out_path.name}")
        else:
            print(f"Ch{ch}: {len(findings)} findings → {out_path} [VALIDATED]")
            for p in findings:
                print(f"  {p['finding_id']:30s}  {p['step1_verdict']:15s}  "
                      f"{p['text'][:60]}...")

    if failed:
        print(f"\nERROR: Some batches failed validation and were deleted.")
        print(f"Fix the underlying data issue before retrying.")
        return 1

    total = sum(len(by_chapter[ch]) for ch in chapters)
    print(f"\nTotal: {total} findings across {len(chapters)} chapters")
    return 0


STEP2_REQUIRED_FIELDS = {
    "qa_history": "Q&A history (global + chapter)",
    "anti_pattern_rules": "Anti-pattern rules",
    "chapter_inventory": "Chapter argument inventory",
    "cross_chapter_inventories": "Cross-chapter inventories",
    "chapter_text": "Full chapter text",
    "step2_rules": "Step 2 verdict rules",
    "findings": "Findings to evaluate",
}


def validate_step2_batch(path: Path) -> list[str]:
    """Validate a Step 2 batch file has all required context.

    Returns a list of error strings. Empty list = valid.
    """
    errors = []
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError) as e:
        return [f"Cannot read/parse: {e}"]

    if not isinstance(data, dict):
        return [f"Top-level type is {type(data).__name__}, expected dict"]

    # Check required keys exist
    for key, label in STEP2_REQUIRED_FIELDS.items():
        if key not in data:
            errors.append(f"MISSING KEY: '{key}' ({label})")

    # Check non-empty values for critical text fields
    qa = data.get("qa_history", "")
    if not qa or (isinstance(qa, str) and len(qa.strip()) == 0):
        errors.append(f"EMPTY: qa_history — evaluator has no Q&A decision history")

    ap = data.get("anti_pattern_rules")
    if not ap:
        errors.append(f"EMPTY: anti_pattern_rules — evaluator has no anti-pattern rules")

    inv = data.get("chapter_inventory", [])
    if not inv or (isinstance(inv, list) and len(inv) == 0):
        errors.append(f"EMPTY: chapter_inventory — evaluator has no argument inventory")

    ct = data.get("chapter_text", "")
    if not ct or (isinstance(ct, str) and len(ct) < 100):
        errors.append(f"EMPTY/SHORT: chapter_text — {len(ct)} chars (need 100+)")

    findings = data.get("findings", [])
    if not findings or not isinstance(findings, list) or len(findings) == 0:
        errors.append(f"EMPTY: findings — nothing to evaluate")

    rules = data.get("step2_rules")
    if not rules:
        errors.append(f"EMPTY: step2_rules — evaluator has no verdict definitions")

    cross = data.get("cross_chapter_inventories")
    if not cross or (isinstance(cross, dict) and len(cross) == 0):
        errors.append(f"EMPTY: cross_chapter_inventories — cannot route wrong-chapter")

    # Check for WRONG key names (ad-hoc assembly artifacts)
    wrong_keys = {
        "qa_content": "qa_history",
        "anti_patterns": "anti_pattern_rules",
        "inventory": "chapter_inventory",
    }
    for wrong, correct in wrong_keys.items():
        if wrong in data and correct not in data:
            errors.append(
                f"WRONG KEY: '{wrong}' found — should be '{correct}'. "
                f"This batch was likely assembled ad-hoc, not by build_coverage.py"
            )

    return errors


def cmd_validate(args):
    """Validate Step 2 batch files have required context."""
    target = args.validate_path
    if not target:
        target = str(COVERAGE_DIR / "step2_batches")

    target_path = Path(target)
    if target_path.is_file():
        files = [target_path]
    elif target_path.is_dir():
        files = sorted(target_path.glob("*.json"))
        # Exclude verdict files
        files = [f for f in files if "verdict" not in f.name]
    else:
        print(f"ERROR: {target} not found", file=sys.stderr)
        return 1

    if not files:
        print(f"No batch files found in {target}")
        return 1

    total_errors = 0
    total_valid = 0
    for f in files:
        errors = validate_step2_batch(f)
        if errors:
            total_errors += 1
            print(f"\nFAIL: {f.name}")
            for e in errors:
                print(f"  - {e}")
        else:
            total_valid += 1
            print(f"OK: {f.name}")

    print(f"\n{'=' * 60}")
    print(f"VALID: {total_valid} | FAILED: {total_errors} | TOTAL: {len(files)}")
    if total_errors > 0:
        print(f"\nBLOCKED: {total_errors} batch(es) must not be evaluated.")
        print(f"Regenerate with: python scripts/build_coverage.py --embed-prep --chapter N")
        return 1
    else:
        print(f"\nAll batches valid. Safe to evaluate.")
        return 0


def main():
    parser = argparse.ArgumentParser(
        description="DD-0002 coverage pipeline (Step 1 verdicts + Step 2 embed context)"
    )
    parser.add_argument("--status", action="store_true", help="Show pipeline status")
    parser.add_argument("--batches", action="store_true", help="Generate eval batches")
    parser.add_argument("--merge", type=str, help="Merge verdict results from file")
    parser.add_argument("--normalize", action="store_true", help="Normalize formats")
    parser.add_argument("--redistribute", action="store_true",
                        help="Redistribute wrong_chapter findings")
    parser.add_argument("--resolve", action="store_true",
                        help="Generate forced-resolution batches for bouncing findings")
    parser.add_argument("--embed-prep", action="store_true",
                        help="Assemble Step 2 embed context packages")
    parser.add_argument("--validate", action="store_true",
                        help="Validate Step 2 batch files have required context")
    parser.add_argument("--validate-path", type=str, dest="validate_path",
                        help="Path to batch file or directory (default: step2_batches/)")
    parser.add_argument("--batch", type=str,
                        help="Batch file for --embed-prep (findings JSON)")
    parser.add_argument("--round", type=int, default=1,
                        help="Redistribution round number (default: 1)")
    parser.add_argument("--chapter", type=int, help="Limit to specific chapter")
    parser.add_argument("--force", action="store_true",
                        help="Regenerate batches for ALL findings (ignore existing verdicts)")
    args = parser.parse_args()

    if args.status:
        return cmd_status(args)
    elif args.batches:
        return cmd_batches(args)
    elif args.merge:
        return cmd_merge(args)
    elif args.normalize:
        return cmd_normalize(args)
    elif args.redistribute:
        return cmd_redistribute(args)
    elif args.resolve:
        return cmd_resolve(args)
    elif args.embed_prep:
        return cmd_embed_prep(args)
    elif args.validate:
        return cmd_validate(args)
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main() or 0)
